pipeline {
  agent any
  stages {
    
    stage('checkout') { 
      steps {
			withMaven(maven:'maven') {
				sh 'mvn -f  test/pom.xml clean install'
			}
        
      }
    }
    
  }
}