pipeline {
  agent any
   stages {
    stage('Build') { 
      steps {
        withMaven(maven:'maven'){
 				bat 'mvn  -file mulejenkins/pom.xml clean install'
 			}
      }

  }
  tage ('Deploy'){
 		steps {
 			withMaven(maven:'maven'){
 				bat 'mvn -f mule-jenkins-pipeline/pom.xml package deploy  -Dusername=pramod01 -Dpassword=Newuser@123 -Denvironment=dev -DmuleDeploy'
 			}
 		}
 	}
  }
}
