pipeline {
  agent any
   stages {
  stage ('BuildAndDeploy'){
 		steps {
 			withMaven(maven:'maven'){
 				bat 'mvn -file mule-jenkins-pipeline/pom.xml package deploy  -Dusername=pramod02 -Dpassword=Newuser@123 -Denvironment=dev -DmuleDeploy'
 			}
 		}
 	}
  }
}
